raise:
  name: Raise
  description: Start raising the brightness.
  target:
    entity:
      domain: light
      integration: hue
  fields:
    sweep_time:
      name: Sweep
      description: Duration of 0-100% sweep.
      example: 5
      required: false
      selector:
        number:
          min: 0.1
          step: any
          unit_of_measurement: s
          mode: box
    limit:
      name: Maximum brightness limit
      description: Stop transition at limit.
      example: 100
      required: false
      selector:
        number:
          min: 1
          max: 100
          step: 0.2
          unit_of_measurement: "%"

lower:
  name: Lower
  description: Start lowering the brightness.
  target:
    entity:
      domain: light
      integration: hue
  fields:
    sweep_time:
      name: Sweep
      description: Duration of 100-0% sweep.
      example: 5
      required: false
      selector:
        number:
          min: 0.1
          step: any
          unit_of_measurement: s
          mode: box
    limit:
      name: Minimum brightness limit
      description: Light turns off at 0%. Choose 0.4%+ to keep standard Hue lights on, and 2%+ for Essential series.
      example: 0.4
      required: false
      selector:
        number:
          min: 0
          max: 99
          step: 0.2
          unit_of_measurement: "%"

stop:
  name: Stop
  description: Stop a brightness transition.
  target:
    entity:
      domain: light
      integration: hue

set_attributes:
  name: Set attributes
  description: Set brightness and/or color temperature without turning on.
  target:
    entity:
      domain: light
      integration: hue
  fields:
    brightness:
      name: Brightness
      description: Brightness level.
      example: 50
      required: false
      selector:
        number:
          min: 0.4
          max: 100
          step: 0.2
          unit_of_measurement: "%"
    min_brightness:
      name: Minimum brightness
      description: If current brightness is below this, raise it.
      example: 20
      required: false
      selector:
        number:
          min: 0.4
          max: 100
          step: 0.2
          unit_of_measurement: "%"
    max_brightness:
      name: Maximum brightness
      description: If current brightness is above this, lower it.
      example: 80
      required: false
      selector:
        number:
          min: 0.4
          max: 100
          step: 0.2
          unit_of_measurement: "%"
    color_temp_kelvin:
      name: Color temperature
      description: Color temperature in Kelvin.
      example: 2800
      required: false
      selector:
        number:
          min: 2200
          max: 6535
          step: 10
          unit_of_measurement: K

get_attributes:
  name: Get attributes
  description: Get brightness and color temperature from Hue bridge, even when lights are off.
  target:
    entity:
      domain: light
      integration: hue
